### ISSUE TITLE
Update BottomNavigation and WorkOutFab after merge with tracking branch

### ISSUE THREAD

**Issue by devtobi** [mobileappdevhm20/team-project-team_7#31]
The logic is implemented, however the BottomNavigation and WorkoutFab need to be adjusted to the new screens.

- [x]  Add History Screen to bottomNavigationBar
- [x]  Add functionality to WorkoutFab
- [x]  Add fab button to Workout Screen for StartStop of the workout

**Comment by devtobi** [comment]
Everything was implemented.
Closing. 😄
